### ISSUE TITLE
No file exists and throws up an AssertionError with --preproc flag

### ISSUE THREAD

**Issue by timatcambrio** [DIUx-xView/xview3-dev#7]
When running `create_xview3_data.py` with the `--preproc` flag, we get the following error:
```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/xview3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/miniconda3/envs/xview3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/xview3-dev/dev/create_xview3_data.py", line 479, in <module>
    main()
  File "/home/ubuntu/xview3-dev/dev/create_xview3_data.py", line 437, in main
    img_path = get_scihub_grd_path(args.download_path,
  File "/home/ubuntu/xview3-dev/dev/create_xview3_data.py", line 215, in get_scihub_grd_path
    assert len(filenames) == 1
AssertionError
```

This corresponds to the following line:  https://github.com/DIUx-xView/xview3-dev/blob/d436f79ce32556d6b6744aea01ca3a6870c6efb2/dev/create_xview3_data.py#L215

As far as I can tell, the directory from which the variable `filenames` is constructed was created by the script itself and no file are added to it by the time the script wants exactly one file in it.

**Comment by jdunnmon** [comment]
I've seen this happen once when the script was run, didn't complete, and then was run again.  Can you clean the output directory and rerun?

**Comment by timatcambrio** [comment]
Here is the error when I remove the `test_output` directory and run the script:
```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/xview3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/miniconda3/envs/xview3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/xview3-dev/dev/create_xview3_data.py", line 479, in <module>
    main()
  File "/home/ubuntu/xview3-dev/dev/create_xview3_data.py", line 437, in main
    img_path = get_scihub_grd_path(args.download_path,
  File "/home/ubuntu/xview3-dev/dev/create_xview3_data.py", line 203, in get_scihub_grd_path
    in os.listdir(parent_path)
FileNotFoundError: [Errno 2] No such file or directory: 'test_output/S1A_IW_GRDH_1SDV_20210104T001845_20210104T001910_035980_043717_4653'
```

**Comment by timatcambrio** [comment]
Closing the issue because removing both the `test_download` and the `test_output` directories and re-run was successful.
